int bazait=6;
int pauza1=900;
int pauza2=700;
int pauza3=300;
int pauza4=200;
int pauza5=100;
int pauza6=50;
int pauza7=1;



void setup() {
  // put your setup code here, to run once:
pinMode(bazait, OUTPUT);
}

void loop() {
  // put your main code here, to run repeatedly:
digitalWrite(bazait, HIGH);
delay(pauza1);
digitalWrite(bazait, LOW);
delay(pauza1);
digitalWrite(bazait, HIGH);
delay(pauza1);
digitalWrite(bazait, LOW);
delay(pauza1);
digitalWrite(bazait, HIGH);
delay(pauza1);
digitalWrite(bazait, LOW);
delay(pauza1);
digitalWrite(bazait, HIGH);
delay(pauza1);
digitalWrite(bazait, LOW);
delay(pauza1);

digitalWrite(bazait, HIGH);
delay(pauza2);
digitalWrite(bazait, LOW);
delay(pauza2);
digitalWrite(bazait, HIGH);
delay(pauza2);
digitalWrite(bazait, LOW);
delay(pauza2);
digitalWrite(bazait, LOW);
delay(pauza2);
digitalWrite(bazait, HIGH);
delay(pauza2);
digitalWrite(bazait, LOW);
delay(pauza2);
digitalWrite(bazait, HIGH);
delay(pauza2);
digitalWrite(bazait, LOW);
delay(pauza2);

digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, HIGH);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);
digitalWrite(bazait, LOW);
delay(pauza3);

digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);
digitalWrite(bazait, HIGH);
delay(pauza4);
digitalWrite(bazait, LOW);
delay(pauza4);

digitalWrite(bazait, HIGH);
delay(pauza5);
digitalWrite(bazait, LOW);
delay(pauza5);
digitalWrite(bazait, HIGH);
delay(pauza5);
digitalWrite(bazait, LOW);
delay(pauza5);
digitalWrite(bazait, HIGH);
delay(pauza5);
digitalWrite(bazait, LOW);
delay(pauza5);
digitalWrite(bazait, HIGH);
delay(pauza5);
digitalWrite(bazait, LOW);
delay(pauza5);
digitalWrite(bazait, HIGH);
delay(pauza5);
digitalWrite(bazait, LOW);
delay(pauza5);
digitalWrite(bazait, HIGH);
delay(pauza5);
digitalWrite(bazait, LOW);
delay(pauza5);

digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, LOW);
delay(pauza6);
digitalWrite(bazait, HIGH);
delay(pauza6);

digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);
delay(pauza7);
digitalWrite(bazait, LOW);
delay(pauza7);
digitalWrite(bazait, HIGH);




}
